### ISSUE TITLE
organizers profile pg 

### ISSUE THREAD

**Issue by ms-solly** [ms-solly/curly-train#5]
#### Description:
The organizer page provides information about the organizer and lists past and future tournaments held by them. The structure mirrors the tournament page(#4 ) but is more focused on the organizer’s profile.

#### To-Do:
- [ ] Create a block of text describing the organizer with a brief bio or introduction.
- [ ] Build a table listing past and planned tournaments organized by the entity.
- [ ] Ensure the layout is consistent with the tournament page for easy navigation.
- [ ] Make sure the page is responsive on all devices.
